repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-tidy-imports
          - flake8-bugbear
          - flake8-pyproject

